filter/urls.py
from django.urls import path
from .views import index, JsonFilterMoviesView




urlpatterns = [
    path('', index, name='index'),
    path('json_filter/', JsonFilterMoviesView.as_view(), name='json_filter')
]

filter_ajax/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filter.urls')),
]

filter/models.py
from django.db import models

class Table(models.Model):
    date = models.DateField()
    title = models.CharField(max_length=255)
    count = models.IntegerField()
    distance = models.IntegerField()

    def __str__(self):
        return self.title

class Genre(models.Model):
    name = models.CharField(max_length=255)

filter/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import JsonResponse
from .models import Table, Genre
from time import time
from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger, EmptyPage

def index(request):
    now = time()
    genres = Genre.objects.all()
    return render(request, 'filter/index.html', {'genres': genres, 'now': now})

class JsonFilterMoviesView(ListView):
    model = Table
    paginate_by = 5
    """Фильтр фильмов в json"""
    def get_queryset(self):
        fields = {'1': 'title', '2': 'count', '3': 'distance'}
        column = fields.get(self.request.GET.get('title'))
        condition = self.request.GET.get('count')
        value = self.request.GET.get('value')
        queryset = Table.objects.all()
        if column == '' or condition == '' or value == '':
            pass
        elif condition == '1':
            queryset = Table.objects.all().extra(where=[f'{column} > {value}'])
        elif condition == '2':
            queryset = Table.objects.extra(where=[f'{column} < {value}'])
        elif condition == '3':
            queryset = Table.objects.extra(where=[f'{column} = {value}'])
        elif condition == '4':
            queryset = Table.objects.extra(where=[f'{column} LIKE "%{value}%"'])
        return queryset.distinct().values('title', 'date', 'count', 'distance')

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        paginator = Paginator(queryset, self.paginate_by)
        page = request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)
        queryset = list(queryset)
        # queryset = list(self.get_queryset())
        # print(queryset)
        return JsonResponse({"movies": queryset, 'page': page}, safe=False)

templates/filter.html
{% extends "table/index.html" %}

{% block content %}
{#    <h1>hello, this is filter.html</h1>#}
{#    <form method="get">#}
{#        {{ filter.form.as_p }}#}
{#        <input type="submit" />#}
{#    </form>#}


    <form method="get">
        <p>
    <label for="id_title">column:</label>
    <select name="title" id="id_title">
  <option value="">---------</option>

  <option value="1">title</option>

  <option value="2" selected>count</option>

  <option value="3">distance</option>

</select>


  </p>


  <p>
    <label for="id_count">condition:</label>
    <select name="count" id="id_count">
  <option value="">---------</option>

  <option value="1">&gt;</option>

  <option value="2">&lt;</option>

  <option value="3" selected>==</option>

  <option value="4">in</option>

</select>
  </p>
  <p>
    <label for="id_distance">Value:</label>
    <input type="text" name="value" id="id_distance">

  </p>
        <input type="submit" />
    </form>
{#    {% for obj in filter.qs %}#}
    {% for obj in filter %}
        {{ obj.title }} - ${{ obj.count }}<br />
    {% endfor %}
{% endblock %}

templates/filter/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'json_filter' %}" method="get" name="filter">
        <p>
    <label for="id_title">column:</label>
    <select name="title" id="id_title">
  <option value="">---------</option>

  <option value="1">title</option>

  <option value="2" selected>count</option>

  <option value="3">distance</option>

</select></p>
    <p>
    <label for="id_count">condition:</label>
    <select name="count" id="id_count">
  <option value="">---------</option>

  <option value="1">&gt;</option>

  <option value="2">&lt;</option>

  <option value="3" selected>==</option>

  <option value="4">in</option>
</select>
  </p>

  <p>
    <label for="id_distance">Value:</label>
    <input type="text" name="value" id="id_distance">

  </p>
        <button type="submit">Найти</button>
</form>

{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
            <span class="money editContent" >Flat 50% Off</span>
            <a href="moviesingle.html" class="btn" >Now</a>
        </div>-->
    </div>
{% endblock movie %}

<script src="{% static 'js/scripts.js' %}?{{ now }}"></script>
<script src="http://twitter.github.io/hogan.js/builds/3.0.1/hogan-3.0.1.js"></script>
</body>
</html>

templates/table.html
{% load static %}
<table>
    {% for row in table_list %}
        <tr>
            <td>{{ row.title }}</td>
        </tr>
    {% endfor %}
</table>
<h1>now {{ now }}</h1>
{% block pagination %}
    <input type="submit" id="update" value="update" data-type="2">
    {% if is_paginated %}
        <div class = "pagination">
            <span class = "page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
{#                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>#}
                    <button class = "button" data-type="{{ page_obj.next_page_number }}">Следующий </button>
  {#                  <a href="{% static 'js/my_ajax.js'%}?page={{ page_obj.next_page_number }}">Следующая</a>#}
                {% endif %}
            </span>
        </div>
<script src="{% static 'js/table.js' %}?{{ now }}"></script>
{% endif %}
{% endblock %}
{#<span> <input type="submit" class="button" value="предыдущая" data-type="prev"> </span>#}
{#<span> <input type="submit" class="button" value="следующая" data-type="nex"> </span>#}